API_KEY_HEADER = "X-API-Key"
REQUEST_ID_HEADER = "X-Request-ID"
PROCESS_TIME_HEADER = "X-Process-Time"

RATE_LIMIT_LIMIT_HEADER = "X-RateLimit-Limit"
RATE_LIMIT_REMAINING_HEADER = "X-RateLimit-Remaining"
RATE_LIMIT_RESET_HEADER = "X-RateLimit-Reset"

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

LEGACY_RATE_LIMIT_PER_MINUTE = 60
